name: CI
on:
  push:
    branches:
      - master

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'

    - run: npm -v
    - run: npm install -g npm@8
    - run: npm -v
    - run: npm install
    - run: npm install --workspaces
    - run: npm run build
    - run: npm run doc
    - run: npm run coverage
    - run: npm run bundle
    - run: npm run bundle:min

    - run: cp -rp packages/baidu-map/dist/* website/build
    - run: cp -rp coverage website/build

    - name: Create Coverage Badges
      uses: jaywcjlove/coverage-badges-cli@main
      with:
        output: website/build/badges.svg

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        output: website/build/CONTRIBUTORS.svg
        avatarSize: 42

    # node@v24.0.0+ 
    # https://gist.github.com/jaywcjlove/a178278521a6f72c74525d3f1d9c4bf9
    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/baidu-map/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/api-loader/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/circle/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/copyright-control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/curve-line/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/custom-overlay/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/drawing-manager/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/geolocation-control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/ground-overlay/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/info-window/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/label/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/map/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/marker/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/navigation-control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/overview-map-control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/panorama-control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/point-collection/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/polygon/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/polyline/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/require-script/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/scale-control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/tile-layer/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/type-control/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/types/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/utils/

    - run: npm publish --access public --provenance
      continue-on-error: true
      working-directory: packages/with-map/

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@main
      with:
        package-path: ./packages/baidu-map/package.json

    - name: get tag version
      id: tag_version
      uses: jaywcjlove/changelog-generator@main

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build
        commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (renovate-bot|Renovate Bot)
        head-ref: ${{steps.create_tag.outputs.version}}
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          [![Buy me a coffee](https://img.shields.io/badge/Buy%20me%20a%20coffee-048754?logo=buymeacoffee)](https://jaywcjlove.github.io/#/sponsor) [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-baidu-map@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/react-baidu-map)](https://bundlephobia.com/result?p=@uiw/react-baidu-map@${{steps.create_tag.outputs.versionNumber}})
        
          Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/idoc/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
          Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  
          
          ```bash
          npm i @uiw/react-baidu-map@${{steps.create_tag.outputs.versionNumber}}
          ```

          ${{ steps.changelog.outputs.changelog }}


          Document react-baidu-map@${{ steps.create_tag.outputs.version }}:
          https://raw.githack.com/uiwjs/react-baidu-map/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html
